## 1. 문제 정의 -당뇨병을 예측한다

## 2. 데이터 수집

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
plt.rc('font',family='Malgun Gothic')
plt.rcParams['axes.unicode_minus']=False
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_df = pd.read_excel('당뇨병.xlsx',sheet_name='train')
test_df = pd.read_excel('당뇨병.xlsx',sheet_name='test')

In [3]:
train_df.head()

ID  임신  글루코스(탄수화물 화합물)  혈압  피부두께  인슐린   BMI    가족력  나이  당뇨여부
0   1   6             148  72    35    0  33.6  0.627  50     1
1   3   1              89  66    23   94  28.1  0.167  21     0
2   4   0             137  40    35  168  43.1  2.288  33     1
3   6   2             197  70    45  543  30.5  0.158  53     1
4   8   5             166  72    19  175  25.8  0.587  51     1

In [4]:
test_df.head()

ID  임신  글루코스(탄수화물 화합물)  혈압  피부두께  인슐린   BMI    가족력  나이  당뇨여부
0   2   1              85  66    29    0  26.6  0.351  31     0
1   5   3              78  50    32   88  31.0  0.248  26     1
2   7   1             189  60    23  846  30.1  0.398  59     1
3   9   0             118  84    47  230  45.8  0.551  31     1
4  10   1             103  30    38   83  43.3  0.183  33     0

In [5]:
labels=['정상','당뇨']

In [6]:
x_train=train_df.drop(['ID','당뇨여부'],axis=1)
x_test=test_df.drop(['ID','당뇨여부'],axis=1)
y_train=train_df['당뇨여부']
y_test=test_df['당뇨여부']

In [7]:
x_train.head()

임신  글루코스(탄수화물 화합물)  혈압  피부두께  인슐린   BMI    가족력  나이
0   6             148  72    35    0  33.6  0.627  50
1   1              89  66    23   94  28.1  0.167  21
2   0             137  40    35  168  43.1  2.288  33
3   2             197  70    45  543  30.5  0.158  53
4   5             166  72    19  175  25.8  0.587  51

#### 모델링

##### random forest(분류)

In [8]:
rf = RandomForestClassifier(max_depth=3)
#모델 생성
rf.fit(x_train,y_train)
#모델 학습

#과대 적합을 해소하기 위해서는 
#max_depth나 learning_rate등의 하이퍼파라미터를 주면 된다.

RandomForestClassifier(max_depth=3)

In [9]:
pred=rf.predict(x_test)
pred
#예측값 산출

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [10]:
rf.score(x_train,y_train)
#분류모델이기 때문에 model.score()의 평가지표는 Accuracy(정확도)
#과대 적합

0.8351063829787234

In [11]:
rf.score(x_test,y_test)
#분류모델이기 때문에 model.score()의 평가지표는 Accuracy(정확도)

0.7515527950310559

#### ada boost

##### 분류모델

In [12]:
from sklearn.ensemble import AdaBoostClassifier

In [13]:
ada = AdaBoostClassifier(n_estimators=1000,random_state=0,
                         learning_rate=0.01).fit(x_train,y_train)
#모델 선정,1000개의 트리,0번시드,학습률 0.01
#모델 학습

In [14]:
pred=rf.predict(x_test)
pred
#예측값 산출

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [15]:
ada.score(x_train,y_train)
#분류모델이기 때문에 model.score()의 평가지표는 Accuracy(정확도)

0.8297872340425532

In [16]:
ada.score(x_test,y_test)
#분류모델이기 때문에 model.score()의 평가지표는 Accuracy(정확도)

0.7577639751552795

##### 회귀모델

In [17]:
from sklearn.ensemble import AdaBoostRegressor

In [18]:
ada = AdaBoostRegressor(n_estimators=100,learning_rate=0.01,
                          random_state=0).fit(x_train,y_train)

In [19]:
pred=rf.predict(x_test)
pred
#예측값 산출

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [20]:
ada.score(x_train,y_train)
#회귀모델의 model.score()=r2_score

0.49880271724608594

In [21]:
ada.score(x_test,y_test)
#회귀모델의 model.score()=r2_score

0.24518236016289818

#### Gradient Boosting Model

In [22]:
from sklearn.ensemble import GradientBoostingClassifier

In [23]:
gbm = GradientBoostingClassifier(n_estimators=1000
                                 ,learning_rate=0.01,
                                 max_depth=2,
                                 random_state=0).fit(x_train,y_train)
#모델 선정 및 학습

In [24]:
gbm.score(x_train,y_train)
#분류모델의 기준 = Accuracy(정확도)

0.898936170212766

In [25]:
gbm.score(x_test,y_test)
#분류모델의 기준 = Accuracy(정확도)

0.7515527950310559

##### xgboost

In [26]:
import xgboost as xgb

In [27]:
xg = xgb.XGBClassifier(n_estimators=100,random_state=0
                       ,learning_rate=0.01).fit(x_train,y_train)
#모델 선정 및 학습

In [28]:
xg.score(x_train,y_train)
#분류모델의 기준 = Accuracy(정확도)

0.9042553191489362

In [29]:
xg.score(x_test,y_test)
#분류모델의 기준 = Accuracy(정확도)

0.7763975155279503

##### light GBM

In [30]:
from lightgbm import LGBMClassifier

In [31]:
lgb = LGBMClassifier(n_estimators=1000,random_state=0,
                    learning_rate=0.01,max_depth=3).fit(x_train,y_train)

In [32]:
lgb.score(x_train,y_train)
#분류모델의 기준 = Accuracy(정확도)

0.9069148936170213

In [33]:
lgb.score(x_test,y_test)
#분류모델의 기준 = Accuracy(정확도)

0.7763975155279503