## 1.목표 - 현대차 가격 예측하기

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.ensemble import RandomForestRegressor

## 2.데이터 수집 

In [2]:
train_df = pd.read_excel('현대차_가격.xlsx',sheet_name='train')
test_df = pd.read_excel('현대차_가격.xlsx',sheet_name='test')

In [3]:
train_df

가격    년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   1885  2015  준중형  11.8  172  21.0  가솔린      0  1999  1300  자동
1   2190  2015  준중형  12.3  204  27.0  가솔린      0  1591  1300  자동
2   1135  2015   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
3   1645  2014   소형  14.0  140  17.0  가솔린      0  1591  1090  자동
4   1960  2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
..   ...   ...  ...   ...  ...   ...  ...    ...   ...   ...  ..
66  3802  2015   중형   8.5  290  34.8  가솔린      0  3342  1901  자동
67  1270  2012   소형  13.3  108  13.9  가솔린      0  1396  1040  자동
68  2430  2015  준중형  12.8  186  41.0   디젤      0  1995  1665  자동
69  2870  2015   중형  17.7  156  19.3  가솔린      1  1999  1585  자동
70  3254  2015   대형  13.8  202  45.0   디젤      0  2199  1691  자동

[71 rows x 11 columns]

In [4]:
test_df

가격    년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0    1915  2015   대형   6.8  159  23.0  LPG      0  2359  1935  수동
1    1164  2012   소형  13.3  108  13.9  가솔린      0  1396  1035  자동
2    2817  2015   중형  14.4  184  41.0   디젤      0  1995  1792  자동
3    2160  2015   대형  10.9  175  46.0   디젤      0  2497  2210  수동
4    1915  2015   대형   6.4  159  23.0  LPG      0  2359  1935  자동
5    1560  2015   소형  18.0  136  30.6   디젤      0  1582  1160  자동
6    2260  2015  준중형  13.9  184  41.0   디젤      0  1995  1611  수동
7    1430  2015   대형   8.9  133  26.5   디젤      0  2497  1696  수동
8    2260  2015  준중형  12.5  184  41.0   디젤      0  1995  1611  자동
9    1690  2015  준중형  12.8  215  21.3  가솔린      0  1999  1216  수동
10   2255  2015   중형  11.6  168  20.5  가솔린      0  1999  1460  자동
11   3590  2015   중형   8.9  290  34.8  가솔린      0  3342  1832  자동
12   1445  2015   소형  18.0  136  30.6   디젤      0  1582  1190  자동
13   1610  2015  준중형  16.2  128  28.5   디젤      0  1582  1305  자동
14   4897  2015   대형   8.6  282  35.4  가솔린      0  3342  1970  자동
15   1445  2015   소형  19.0  136  30.6   디젤      0  1582  1190  수동
16   2080  2015  준중형  14.4  184  41.0   디젤      0  1995  1548  수동
17   1135  2015   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
18   1111  2014   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
19   2190  2015  준중형  12.4  204  27.0  가솔린      0  1591  1300  수동
20   1111  2014   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
21   1845  2015  준중형  13.0  140  17.0  가솔린      0  1591  1225  수동
22  14570  2015   대형   7.4  416  52.0  가솔린      0  5038  2145  자동
23   1890  2015  준중형  11.8  172  21.0  가솔린      0  1999  1325  자동
24   1690  2015  준중형  12.4  215  21.3  가솔린      0  1999  1216  자동
25   1410  2015  준중형  14.0  140  17.0  가솔린      0  1591  1210  자동
26   6910  2015   대형   8.9  334  40.3  가솔린      0  3778  1915  자동
27   2545  2015   대형   8.7  175  46.0   디젤      0  2497  2383  수동
28   1960  2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
29    870  2010   소형  13.0   95  12.7  가솔린      0  1399  1046  자동
30   2879  2015   중형  14.8  200  43.0   디젤      0  2199  1760  수동

In [5]:
x_train = train_df.drop(['가격'],axis=1)
x_test = test_df.drop(['가격'],axis=1)
y_train = train_df['가격']
y_test = test_df['가격']
#데이터 분할

In [6]:
x_train

년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   2015  준중형  11.8  172  21.0  가솔린      0  1999  1300  자동
1   2015  준중형  12.3  204  27.0  가솔린      0  1591  1300  자동
2   2015   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
3   2014   소형  14.0  140  17.0  가솔린      0  1591  1090  자동
4   2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
..   ...  ...   ...  ...   ...  ...    ...   ...   ...  ..
66  2015   중형   8.5  290  34.8  가솔린      0  3342  1901  자동
67  2012   소형  13.3  108  13.9  가솔린      0  1396  1040  자동
68  2015  준중형  12.8  186  41.0   디젤      0  1995  1665  자동
69  2015   중형  17.7  156  19.3  가솔린      1  1999  1585  자동
70  2015   대형  13.8  202  45.0   디젤      0  2199  1691  자동

[71 rows x 10 columns]

In [7]:
x_test

년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   2015   대형   6.8  159  23.0  LPG      0  2359  1935  수동
1   2012   소형  13.3  108  13.9  가솔린      0  1396  1035  자동
2   2015   중형  14.4  184  41.0   디젤      0  1995  1792  자동
3   2015   대형  10.9  175  46.0   디젤      0  2497  2210  수동
4   2015   대형   6.4  159  23.0  LPG      0  2359  1935  자동
5   2015   소형  18.0  136  30.6   디젤      0  1582  1160  자동
6   2015  준중형  13.9  184  41.0   디젤      0  1995  1611  수동
7   2015   대형   8.9  133  26.5   디젤      0  2497  1696  수동
8   2015  준중형  12.5  184  41.0   디젤      0  1995  1611  자동
9   2015  준중형  12.8  215  21.3  가솔린      0  1999  1216  수동
10  2015   중형  11.6  168  20.5  가솔린      0  1999  1460  자동
11  2015   중형   8.9  290  34.8  가솔린      0  3342  1832  자동
12  2015   소형  18.0  136  30.6   디젤      0  1582  1190  자동
13  2015  준중형  16.2  128  28.5   디젤      0  1582  1305  자동
14  2015   대형   8.6  282  35.4  가솔린      0  3342  1970  자동
15  2015   소형  19.0  136  30.6   디젤      0  1582  1190  수동
16  2015  준중형  14.4  184  41.0   디젤      0  1995  1548  수동
17  2015   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
18  2014   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
19  2015  준중형  12.4  204  27.0  가솔린      0  1591  1300  수동
20  2014   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
21  2015  준중형  13.0  140  17.0  가솔린      0  1591  1225  수동
22  2015   대형   7.4  416  52.0  가솔린      0  5038  2145  자동
23  2015  준중형  11.8  172  21.0  가솔린      0  1999  1325  자동
24  2015  준중형  12.4  215  21.3  가솔린      0  1999  1216  자동
25  2015  준중형  14.0  140  17.0  가솔린      0  1591  1210  자동
26  2015   대형   8.9  334  40.3  가솔린      0  3778  1915  자동
27  2015   대형   8.7  175  46.0   디젤      0  2497  2383  수동
28  2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
29  2010   소형  13.0   95  12.7  가솔린      0  1399  1046  자동
30  2015   중형  14.8  200  43.0   디젤      0  2199  1760  수동

### 3.데이터 인코딩

#### One_hot encoding

In [8]:
transformer = make_column_transformer((OneHotEncoder(),
                                       ['종류','연료','변속기']))
#One hot 인코딩을 위해 transformer 모델을
#make_column_transformer((OneHotEncoder(),[바꾸려고하는 칼럼명]))
#으로 변환

In [9]:
transformer.fit(x_train)
#모델 학습

ColumnTransformer(transformers=[('onehotencoder', OneHotEncoder(),
                                 ['종류', '연료', '변속기'])])

In [10]:
x_train = transformer.transform(x_train)
x_test = transformer.transform(x_test)
#transformer 모델의 transform 내장함수로 x_train과 x_test를 변경시킴

In [11]:
x_train

array([[0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0.

## 모델생성

### random Forest

In [12]:
rf = RandomForestRegressor(n_estimators=1000,max_depth=3,
                           max_leaf_nodes=10).fit(x_train,y_train)
#모델 선정, 1000개의 트리, 깊이 = 3, 

In [13]:
pred = rf.predict(x_test)
pred
#예측값 산출

array([2154.27310389, 1376.80352763, 2940.30258736, 2181.21660801,
       2528.68225476, 1455.06271171, 2062.39061263, 2181.21660801,
       2181.68179556, 2049.80451296, 3023.29614954, 3023.29614954,
       1455.06271171, 2181.68179556, 4538.87803887, 1412.224467  ,
       2062.39061263, 1376.80352763, 1376.80352763, 2049.80451296,
       1205.95829974, 2049.80451296, 4538.87803887, 2212.34280477,
       2212.34280477, 2212.34280477, 4538.87803887, 2181.21660801,
       2560.0752746 , 1376.80352763, 2802.1731492 ])

In [14]:
rf.score(x_train,y_train)
#회귀 모델의 model.score()의 기준 = r2_score

0.573901899124329

In [15]:
rf.score(x_test,y_test)
#회귀 모델의 model.score()의 기준 = r2_score

0.423713952852269

In [16]:
new_test=[[2015,'대형',13.3,170,24.0,'LPG',0,2500,2000,'수동']]
new_test=pd.DataFrame(new_test,columns=['년식','종류','연비','마력',
                                        '토크','연료','하이브리드',
                                        '배기량','중량','변속기'] )
#새로운 데이터 생성

In [17]:
new_test=transformer.transform(new_test)

#새로운 데이터 One-hot Encoding

In [18]:
y_predict = rf.predict(new_test)
y_predict
#예측값 산출

array([2154.27310389])

### ada boost

In [19]:
from sklearn.ensemble import AdaBoostRegressor

In [20]:
ada = AdaBoostRegressor(n_estimators=1000,learning_rate=0.01
                       ,random_state=0).fit(x_train,y_train)
#모델 선정,1000개의 트리, 학습률 0.01, 0번시드, 모델 학습

In [21]:
pred = ada.predict(x_test)
pred
#예측값 산출

array([1910.        , 1341.2       , 3084.33333333, 1955.71428571,
       2438.95454545, 1364.88888889, 2059.92307692, 1955.71428571,
       2082.89473684, 2032.        , 2857.5       , 2857.5       ,
       1364.88888889, 2082.89473684, 6120.42105263, 1343.22222222,
       2059.92307692, 1341.2       , 1341.2       , 2032.        ,
       1282.61538462, 2032.        , 6120.42105263, 2049.09090909,
       2049.09090909, 2049.09090909, 6120.42105263, 1955.71428571,
       2541.66666667, 1341.2       , 3091.        ])

In [22]:
ada.score(x_train,y_train)
#회귀 모델의 model.score()의 기준 = r2_score

0.5186788881226329

In [23]:
ada.score(x_test,y_test)
#회귀 모델의 model.score()의 기준 = r2_score

0.5981887764096637

In [24]:
new_test=[[2015,'대형',13.3,170,24.0,'LPG',0,2500,2000,'수동']]
new_test=pd.DataFrame(new_test,columns=['년식','종류','연비','마력',
                                        '토크','연료','하이브리드',
                                        '배기량','중량','변속기'] )
#새로운 데이터 생성

In [25]:
new_test=transformer.transform(new_test)
#새로운 데이터 One-hot Encoding

In [26]:
y_predict = ada.predict(new_test)
y_predict
#예측값 산출

array([1910.])

### Gradient Boosting Model

In [27]:
from sklearn.ensemble import GradientBoostingRegressor

In [28]:
gbm = GradientBoostingRegressor(n_estimators = 1000, 
                                random_state=0,
                               learning_rate=0.01,
                               max_depth=7).fit(x_train,y_train)
#모델 선정, 트리 1000개,0번시드,학습률 0.01, 트리의 깊이 = 7, 모델 학습

In [29]:
pred = gbm.predict(x_test)
pred
#예측값 산출

array([1882.52616147, 1370.93713725, 3119.25848218, 1919.02458572,
       1882.52616147, 1370.93713725, 2096.6835823 , 1919.02458572,
       2242.01064141, 1647.53630672, 2845.48458756, 2845.48458756,
       1370.93713725, 2242.01064141, 4998.55829934, 1560.0400842 ,
       2096.6835823 , 1370.93713725, 1370.93713725, 1647.53630672,
       1182.05640293, 1647.53630672, 4998.55829934, 1968.77243795,
       1968.77243795, 1968.77243795, 4998.55829934, 1919.02458572,
       2607.11987851, 1370.93713725, 3090.97398902])

In [30]:
gbm.score(x_train,y_train)
#회귀 모델의 model.score()의 기준 = r2_score

0.6032527579957868

In [31]:
gbm.score(x_test,y_test)
#회귀 모델의 model.score()의 기준 = r2_score

0.4849322402561994

In [32]:
new_test=[[2015,'대형',13.3,170,24.0,'LPG',0,2500,2000,'수동']]
new_test=pd.DataFrame(new_test,columns=['년식','종류','연비','마력',
                                        '토크','연료','하이브리드',
                                        '배기량','중량','변속기'] )
#새로운 데이터 생성

In [33]:
new_test=transformer.transform(new_test)
#새로운 데이터 One-hot Encoding

In [34]:
y_predict = gbm.predict(new_test)
y_predict
#예측값 산출

array([1882.52616147])

### XG Boosting

In [35]:
import xgboost as xgb

In [36]:
xg = xgb.XGBRegressor(random_state=0).fit(x_train,y_train)
#모델 선정, 0번시드, 모델학습

In [37]:
pred = xg.predict(x_test)
pred
#예측값 산출

array([1882.4996, 1370.889 , 3119.2856, 1919.0004, 1882.5007, 1437.0973,
       2096.6665, 1919.0004, 2241.9995, 1647.5005, 2845.5   , 2845.5   ,
       1437.0973, 2241.9995, 4998.666 , 1559.9991, 2096.6665, 1370.889 ,
       1370.889 , 1647.5005, 1182.    , 1647.5005, 4998.666 , 1968.7506,
       1968.7506, 1968.7506, 4998.666 , 1919.0004, 2607.125 , 1370.889 ,
       3090.9958], dtype=float32)

In [38]:
xg.score(x_train,y_train)
#회귀 모델의 model.score()의 기준 = r2_score

0.6032527591199182

In [39]:
xg.score(x_test,y_test)
#회귀 모델의 model.score()의 기준 = r2_score

0.4850809005658747

In [40]:
new_test=[[2015,'대형',13.3,170,24.0,'LPG',0,2500,2000,'수동']]
new_test=pd.DataFrame(new_test,columns=['년식','종류','연비','마력',
                                        '토크','연료','하이브리드',
                                        '배기량','중량','변속기'] )
#새로운 데이터 생성

In [41]:
new_test=transformer.transform(new_test)
#새로운 데이터 One-hot Encoding

In [42]:
y_predict = xg.predict(new_test)
y_predict
#예측값 산출

array([1882.4996], dtype=float32)

### Light GBM

In [43]:
from lightgbm import LGBMRegressor

In [44]:
lgb = LGBMRegressor().fit(x_train,y_train)
#모델 선정,기본값,모델 학습

In [45]:
pred = lgb.predict(x_test)
pred
#예측값 산출

array([2252.11693074, 2524.58881662, 2214.22533179, 2558.71980545,
       2952.30878743, 2214.22533179, 1502.49483346, 2558.71980545,
       2214.22533179, 1392.89669031, 2524.58881662, 2524.58881662,
       2214.22533179, 2214.22533179, 3580.81378861, 1502.49483346,
       1502.49483346, 2524.58881662, 2524.58881662, 1392.89669031,
       1392.89669031, 1392.89669031, 3580.81378861, 2524.58881662,
       2524.58881662, 2524.58881662, 3580.81378861, 2558.71980545,
       3270.45030378, 2524.58881662, 1502.49483346])

In [46]:
lgb.score(x_train,y_train)
#회귀 모델의 model.score()의 기준 = r2_score
#과소적합

0.26803621675337663

In [47]:
lgb.score(x_test,y_test)
#회귀 모델의 model.score()의 기준 = r2_score

0.19121671328898493

In [48]:
new_test=[[2015,'대형',13.3,170,24.0,'LPG',0,2500,2000,'수동']]
new_test=pd.DataFrame(new_test,columns=['년식','종류','연비','마력',
                                        '토크','연료','하이브리드',
                                        '배기량','중량','변속기'] )
#새로운 데이터 생성

In [49]:
new_test=transformer.transform(new_test)
#새로운 데이터 One-hot Encoding

In [50]:
y_predict = lgb.predict(new_test)
y_predict
#예측값 산출

array([2252.11693074])