In [1]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd


In [2]:
iris = load_iris()

In [3]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [4]:
df.shape

(150, 4)

### scaler 적용

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df)
train_scale = scaler.transform(df)

In [6]:
train_scale

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [7]:
scale_df = pd.DataFrame(train_scale,columns = iris['feature_names'])
scale_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [8]:
x=scale_df
y=iris.target

In [9]:
x.shape

(150, 4)

In [10]:
y.shape

(150,)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3
                                                ,random_state=0)

In [13]:
x_train.shape

(105, 4)

In [14]:
y_train.shape

(105,)

In [15]:
x_test.shape

(45, 4)

In [16]:
y_test.shape

(45,)

### KNN
- 분류알고리즘
- 예측하려는 데이터 X가 주어지면 ,기존 데이터 중 속성이 비슷한 k개의 이웃을 먼저 찾는 알고리즘
- x를 둘러싼 k개의 가장 가까운 이웃을 찾고, 이웃 데이터가 가장 많이 속해있는 목표 클래스를 예측값으로 결정
- k값에 따라 모델의 예측력이 달라지므로 적합한 k값 설정 필요

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn=KNeighborsClassifier(n_neighbors=5).fit(x_train,y_train)

In [19]:
pred = knn.predict(x_test)
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
acc = accuracy_score(y_test,pred)
print('Accuracy:%.4f'%acc)

Accuracy:0.9778


### 로지스틱 회귀
- 분류 알고리즘/ 회귀x(이름만 회귀임)
- 시그모이드 함수의 출력값(0~1사이)을 각 분류 클래스에 속하게 될 확률값으로 사용
- 1에 가까우면 해당 클래스로 분류, 0에 가까우면 해당 클래스가 아니라고 분류함 

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
lr = LogisticRegression(max_iter=100)
lr.fit(x_train,y_train)

LogisticRegression()

In [24]:
pred = lr.predict(x_test)
print('예측값:',pred)

예측값: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0]


In [25]:
acc= accuracy_score(y_test,pred)
print('Accuracy:%.4f'%acc)

Accuracy:0.9778


In [26]:
prob = lr.predict_log_proba(x_test)
prob
#예측값 별 확률

array([[-8.85689243e+00, -3.48630161e+00, -3.12391837e-02],
       [-5.07091898e+00, -5.09639689e-02, -3.13705532e+00],
       [-4.67322419e-03, -5.36825856e+00, -1.63611173e+01],
       [-1.05505722e+01, -2.46980958e+00, -8.84238061e-02],
       [-2.50980712e-02, -3.69752345e+00, -1.39190101e+01],
       [-1.01763106e+01, -4.60301467e+00, -1.01105799e-02],
       [-1.76118089e-02, -4.04801734e+00, -1.42071310e+01],
       [-4.98851053e+00, -3.35063614e-01, -1.28052414e+00],
       [-6.06282335e+00, -3.13822318e-01, -1.32041920e+00],
       [-3.78625977e+00, -1.14132575e-01, -2.46298797e+00],
       [-6.57802502e+00, -8.37261942e-01, -5.69664480e-01],
       [-3.89130690e+00, -2.75180061e-01, -1.51346436e+00],
       [-4.28501905e+00, -1.62111120e-01, -1.99598363e+00],
       [-5.51670685e+00, -3.64964391e-01, -1.19812471e+00],
       [-4.34788301e+00, -2.96003849e-01, -1.41353702e+00],
       [-9.08186062e-03, -4.70603258e+00, -1.55827222e+01],
       [-4.16258794e+00, -3.37081338e-01

### decision tree
- 의사결정 나무 모델은 트리 알고리즘 사용
- 트리의 각 분기점(node)에는 데이터셋의 피처를 하나씩 위치시킴
- 각 분기점에서 해당 피처에 관한 임의ㅡ이 조건식을 작고 계속 2개 이상 줄기로 가지를 나누면서 데이터 구분
- 이때, 각 분기점에서 분류가 제일 잘 되는 최적의기준을 찾는 과정이 중요

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dt = DecisionTreeClassifier(max_depth=3,
                           random_state=0)

In [29]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [30]:
pred = dt.predict(x_test)
print('예측값:',pred)

예측값: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0]


In [31]:
acc= accuracy_score(y_test,pred)
print('Accuracy:%.4f'%acc)

Accuracy:0.9778
